"""seq_update

Revision ID: abbb29f602f7
Revises: cda2287206c6
Create Date: 2017-08-15 12:03:12.230989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abbb29f602f7'
down_revision = 'cda2287206c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'seq',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint('unique_lesson_seq', 'tasks', ['lesson_id', 'seq'])
    op.drop_constraint('tasks_seq_key', 'tasks', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('tasks_seq_key', 'tasks', ['seq'])
    op.drop_constraint('unique_lesson_seq', 'tasks', type_='unique')
    op.alter_column('tasks', 'seq',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
