"""task_seq

Revision ID: cda2287206c6
Revises: 3d8b44ac2741
Create Date: 2017-08-07 17:44:24.757422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cda2287206c6'
down_revision = '3d8b44ac2741'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('seq', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'tasks', ['seq'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='unique')
    op.drop_column('tasks', 'seq')
    ### end Alembic commands ###
